// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqGBe0KWJ5wiHbNa6G4dtvu4KH2nwCNko',
    appId: '1:134465375720:web:f4dcaa3bbd7e8caf61685d',
    messagingSenderId: '134465375720',
    projectId: 'motivationapp-8b474',
    authDomain: 'motivationapp-8b474.firebaseapp.com',
    storageBucket: 'motivationapp-8b474.appspot.com',
    measurementId: 'G-XV6EX31XK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt9nkTtyD1Z9YDHXc0GtgXKR8Qpt-fJP0',
    appId: '1:134465375720:android:a72403eb5838be6261685d',
    messagingSenderId: '134465375720',
    projectId: 'motivationapp-8b474',
    storageBucket: 'motivationapp-8b474.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVTx2w-PQyaVZkFRMwyRtZLIS9RqBZd2Y',
    appId: '1:134465375720:ios:4b8cb08076f6e54e61685d',
    messagingSenderId: '134465375720',
    projectId: 'motivationapp-8b474',
    storageBucket: 'motivationapp-8b474.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVTx2w-PQyaVZkFRMwyRtZLIS9RqBZd2Y',
    appId: '1:134465375720:ios:4b8cb08076f6e54e61685d',
    messagingSenderId: '134465375720',
    projectId: 'motivationapp-8b474',
    storageBucket: 'motivationapp-8b474.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqGBe0KWJ5wiHbNa6G4dtvu4KH2nwCNko',
    appId: '1:134465375720:web:3888f5ac8393684c61685d',
    messagingSenderId: '134465375720',
    projectId: 'motivationapp-8b474',
    authDomain: 'motivationapp-8b474.firebaseapp.com',
    storageBucket: 'motivationapp-8b474.appspot.com',
    measurementId: 'G-ZFSVZDSJQE',
  );
}
